"use client";

import { motion } from "framer-motion";
import { Navbar, Footer } from "../../../components/Navigation";
import { 
  BookOpen, 
  Search, 
  Activity, 
  Fingerprint, 
  ShieldAlert,
  ArrowRight
} from "lucide-react";
import Link from "next/link";

export default function DeepfakeDetectionGuide() {
  return (
    <div className="min-h-screen bg-obsidian text-slate-300 font-sans selection:bg-amber-signal/20 selection:text-amber-signal">
      <Navbar />
      
      <main className="pt-32 pb-20 px-6 md:px-12 bg-gradient-to-b from-[#030712] to-obsidian">
        <div className="max-w-4xl mx-auto">
          {/* SEO Optimized Header */}
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-16 border-b border-deepslate pb-12 space-y-4"
          >
            <div className="flex items-center gap-3 text-amber-signal font-mono font-bold uppercase tracking-widest text-[10px] mb-4">
              <BookOpen size={14} />
              // FORENSIC KNOWLEDGE HUB
            </div>
            <h1 className="text-4xl md:text-6xl font-black text-white mb-6 leading-tight font-geist uppercase">
              Understanding <span className="text-amber-signal">Deepfake Detection</span> in 2026
            </h1>
            <p className="text-base md:text-lg text-slate-300 leading-relaxed font-sans max-w-2xl">
              An evergreen guide to identifying synthetic media, audio clones, and generative artifacts in professional forensics.
            </p>
          </motion.div>

          {/* Content Sections */}
          <article className="max-w-none space-y-12">
            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-white uppercase font-geist tracking-wide">// What is Deepfake Detection?</h2>
              <p className="text-slate-400 text-sm leading-relaxed font-sans text-justify">
                Deepfake detection is the process of identifying digital media that has been manipulated or generated by artificial intelligence. Unlike traditional photoshop or editing, deepfakes use generative adversarial networks (GANs) or diffusion models to create hyper-realistic content that is often indistinguishable to the human eye.
              </p>
              <div className="border border-deepslate bg-[#030712] p-8 rounded-none relative">
                <div className="absolute top-0 left-0 right-0 h-[1px] bg-deepslate" />
                <h3 className="text-amber-signal font-mono font-bold mb-4 flex items-center gap-2 uppercase text-xs">
                  <Fingerprint size={16} />
                  // The Veridex Approach
                </h3>
                <p className="text-slate-300 text-xs leading-relaxed font-sans">
                  We move beyond simple pattern recognition. Our engine audits the <strong>probabilistic consistency</strong> of the media—looking for artifacts in regions where AI models typically struggle, such as frequency domain coherence and micro-rhythmic cadence in speech.
                </p>
              </div>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-white uppercase font-geist tracking-wide">// 3 Common Deepfake Markers</h2>
              <div className="grid gap-6 font-mono text-[11px]">
                <div className="flex gap-6 p-6 border border-deepslate bg-[#030712] rounded-none relative">
                  <div className="absolute top-0 left-0 right-0 h-[1px] bg-deepslate" />
                  <div className="h-8 w-8 border border-deepslate bg-deepslate/30 flex items-center justify-center text-amber-signal font-bold shrink-0 rounded-none">1</div>
                  <div>
                    <h4 className="text-white font-bold mb-1 font-geist text-xs uppercase">Spectral Anomalies in Audio</h4>
                    <p className="text-[10px] text-slate-500 font-sans mt-1">Synthetic voices often lack natural high-frequency jitter and exhibit robotic "perfect" harmonics that don't occur in human vocal cords.</p>
                  </div>
                </div>
                <div className="flex gap-6 p-6 border border-deepslate bg-[#030712] rounded-none relative">
                  <div className="absolute top-0 left-0 right-0 h-[1px] bg-deepslate" />
                  <div className="h-8 w-8 border border-deepslate bg-deepslate/30 flex items-center justify-center text-amber-signal font-bold shrink-0 rounded-none">2</div>
                  <div>
                    <h4 className="text-white font-bold mb-1 font-geist text-xs uppercase">Boundary Dissociation</h4>
                    <p className="text-[10px] text-slate-500 font-sans mt-1">Detecting blurring or unnatural sharp edges where synthetic faces meet organic hair or clothing backgrounds.</p>
                  </div>
                </div>
                <div className="flex gap-6 p-6 border border-deepslate bg-[#030712] rounded-none relative">
                  <div className="absolute top-0 left-0 right-0 h-[1px] bg-deepslate" />
                  <div className="h-8 w-8 border border-deepslate bg-deepslate/30 flex items-center justify-center text-amber-signal font-bold shrink-0 rounded-none">3</div>
                  <div>
                    <h4 className="text-white font-bold mb-1 font-geist text-xs uppercase">Diffusion Artifacts</h4>
                    <p className="text-[10px] text-slate-500 font-sans mt-1">Micro-level noise patterns (checkering) that are characteristic of the sampling methods used by models like Stable Diffusion or Midjourney.</p>
                  </div>
                </div>
              </div>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-white uppercase font-geist tracking-wide">// Why Evergreen SEO Matters</h2>
              <p className="text-slate-400 text-sm leading-relaxed font-sans text-justify">
                As AI becomes more integrated into business workflows, the need for verification is not a spike—it is a recurring operational requirement. By building specialized knowledge hubs like this, Veridex establishes itself as the primary authority for legal and institutional searchers.
              </p>
              
              <div className="border border-deepslate bg-[#030712] p-8 rounded-none relative overflow-hidden mt-10">
                <div className="absolute top-0 left-0 right-0 h-[1px] bg-amber-signal/30" />
                <div className="flex flex-col md:flex-row items-center justify-between gap-8 font-mono">
                  <div className="max-w-md space-y-2 text-left">
                    <h4 className="text-base font-bold text-white uppercase font-geist">// Ready to verify content?</h4>
                    <p className="text-xs text-slate-400 font-sans">Use our professional forensic auditor to analyze your audio, video, or documents immediately.</p>
                  </div>
                  <div className="shrink-0">
                    <Link href="/audit" className="btn-switch-primary">
                      Initialize Audit
                    </Link>
                  </div>
                </div>
              </div>
            </section>
          </article>
        </div>
      </main>
      
      <Footer />
    </div>
  );
}
