"use client";

import { motion } from "framer-motion";
import { Navbar, Footer } from "../../../components/Navigation";
import { 
  BookOpen, 
  Search, 
  Activity, 
  Fingerprint, 
  ShieldAlert,
  ArrowRight
} from "lucide-react";
import Link from "next/link";

export default function DeepfakeDetectionGuide() {
  return (
    <div className="min-h-screen">
      <Navbar />
      
      <main className="pt-32 pb-20 px-4 md:px-12">
        <div className="max-w-4xl mx-auto">
          {/* SEO Optimized Header */}
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-16 border-b border-white/5 pb-12"
          >
            <div className="flex items-center gap-3 text-teal-400 font-bold uppercase tracking-widest text-xs mb-4">
              <BookOpen size={16} />
              Forensic Knowledge Hub
            </div>
            <h1 className="text-4xl md:text-6xl font-black text-white mb-6 leading-tight">
              Understanding <span className="text-gradient">Deepfake Detection</span> in 2026
            </h1>
            <p className="text-xl text-slate-300 leading-relaxed max-w-2xl">
              An evergreen guide to identifying synthetic media, audio clones, and generative artifacts in professional forensics.
            </p>
          </motion.div>

          {/* Content Sections */}
          <article className="prose prose-invert prose-teal max-w-none">
            <section className="mb-16">
              <h2 className="text-3xl font-bold text-white mb-6">What is Deepfake Detection?</h2>
              <p className="text-slate-400 text-lg leading-relaxed mb-6">
                Deepfake detection is the process of identifying digital media that has been manipulated or generated by artificial intelligence. Unlike traditional photoshop or editing, deepfakes use generative adversarial networks (GANs) or diffusion models to create hyper-realistic content that is often indistinguishable to the human eye.
              </p>
              <div className="glass p-8 rounded-[2rem] border border-teal-500/20 my-10">
                <h3 className="text-teal-400 font-bold mb-4 flex items-center gap-2">
                  <Fingerprint size={20} />
                  The Veridex Approach
                </h3>
                <p className="text-slate-300 text-sm leading-relaxed text-sm">
                  We move beyond simple pattern recognition. Our engine audits the <strong>probabilistic consistency</strong> of the media—looking for artifacts in regions where AI models typically struggle, such as frequency domain coherence and micro-rhythmic cadence in speech.
                </p>
              </div>
            </section>

            <section className="mb-16">
              <h2 className="text-2xl font-bold text-white mb-6">5 Common Deepfake Markers</h2>
              <div className="grid gap-6">
                <div className="flex gap-6 p-6 rounded-2xl bg-white/5 border border-white/5">
                  <div className="h-10 w-10 shrink-0 rounded-full bg-teal-500/20 flex items-center justify-center text-teal-400 font-bold">1</div>
                  <div>
                    <h4 className="text-white font-bold mb-1">Spectral Anomalies in Audio</h4>
                    <p className="text-sm text-slate-400">Synthetic voices often lack natural high-frequency jitter and exhibit robotic "perfect" harmonics that don't occur in human vocal cords.</p>
                  </div>
                </div>
                <div className="flex gap-6 p-6 rounded-2xl bg-white/5 border border-white/5">
                  <div className="h-10 w-10 shrink-0 rounded-full bg-teal-500/20 flex items-center justify-center text-teal-400 font-bold">2</div>
                  <div>
                    <h4 className="text-white font-bold mb-1">Boundary Dissociation</h4>
                    <p className="text-sm text-slate-400">Detecting blurring or unnatural sharp edges where synthetic faces meet organic hair or clothing backgrounds.</p>
                  </div>
                </div>
                <div className="flex gap-6 p-6 rounded-2xl bg-white/5 border border-white/5">
                  <div className="h-10 w-10 shrink-0 rounded-full bg-teal-500/20 flex items-center justify-center text-teal-400 font-bold">3</div>
                  <div>
                    <h4 className="text-white font-bold mb-1">Diffusion Artifacts</h4>
                    <p className="text-sm text-slate-400">Micro-level noise patterns (checkering) that are characteristic of the sampling methods used by models like Stable Diffusion or Midjourney.</p>
                  </div>
                </div>
              </div>
            </section>

            <section className="mb-16">
              <h2 className="text-2xl font-bold text-white mb-6">Why Evergreen SEO Matters for Veridex</h2>
              <p className="text-slate-400 leading-relaxed mb-6">
                As AI becomes more integrated into business workflows, the need for verification is not a spike—it is a recurring operational requirement. By building specialized knowledge hubs like this, Veridex establishes itself as the primary authority for legal and institutional searchers.
              </p>
              <div className="p-1 border-t border-white/10 pt-10 mt-10">
                <div className="flex flex-col md:flex-row items-center justify-between gap-8 bg-gradient-to-r from-teal-900/40 to-slate-900/40 p-8 rounded-3xl border border-teal-500/30">
                  <div className="max-w-md">
                    <h4 className="text-xl font-bold text-white mb-2">Ready to verify your content?</h4>
                    <p className="text-sm text-slate-400">Use our professional forensic auditor to analyze your audio, video, or documents immediately.</p>
                  </div>
                  <Link href="/audit" className="btn-primary flex items-center gap-2 whitespace-nowrap">
                    Initialize Audit <ArrowRight size={18} />
                  </Link>
                </div>
              </div>
            </section>
          </article>
        </div>
      </main>
      
      <Footer />
    </div>
  );
}
