"use client";

import { useState } from "react";
import { X } from "lucide-react";
import { CASE_CATEGORIES, CASE_PRIORITIES } from "@/lib/workspace/constants";
import type { CaseItem } from "@/lib/types/workspace";

export function CaseDialog({ onClose, onCreated }: { onClose: () => void; onCreated: (item: CaseItem) => void }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/workspace/cases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.get("title"), description: form.get("description") || undefined, priority: form.get("priority"), category: form.get("category"), dueDate: form.get("dueDate") || undefined, tags: String(form.get("tags") || "").split(",").map(x => x.trim()).filter(Boolean) }) }); const data = await response.json(); setSaving(false); if (!response.ok) return setError(data.error || "Unable to create case."); onCreated(data.item); onClose(); }
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-label="Create a new case"><form onSubmit={submit} className="w-full max-w-lg border border-deepslate bg-[#030712] p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-lg font-bold text-white">New investigation</h2><p className="mt-1 text-xs text-slate-500">Create the case before adding evidence.</p></div><button type="button" onClick={onClose} aria-label="Close dialog" className="text-slate-400 hover:text-white"><X size={18}/></button></div><label className="block text-xs text-slate-300">Title<input name="title" required autoFocus className="mt-2 w-full border border-deepslate bg-obsidian px-3 py-2 text-sm text-white outline-none focus:border-amber-signal" placeholder="e.g. Q3 vendor media review" /></label><label className="mt-4 block text-xs text-slate-300">Description<textarea name="description" rows={3} className="mt-2 w-full border border-deepslate bg-obsidian px-3 py-2 text-sm text-white outline-none focus:border-amber-signal" /></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs text-slate-300">Priority<select name="priority" className="mt-2 w-full border border-deepslate bg-obsidian px-3 py-2 text-sm text-white">{CASE_PRIORITIES.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label className="text-xs text-slate-300">Category<select name="category" className="mt-2 w-full border border-deepslate bg-obsidian px-3 py-2 text-sm text-white">{CASE_CATEGORIES.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs text-slate-300">Due date<input name="dueDate" type="date" className="mt-2 w-full border border-deepslate bg-obsidian px-3 py-2 text-sm text-white" /></label><label className="text-xs text-slate-300">Tags<input name="tags" className="mt-2 w-full border border-deepslate bg-obsidian px-3 py-2 text-sm text-white" placeholder="legal, priority" /></label></div>{error && <p role="alert" className="mt-4 text-xs text-red-400">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="px-4 py-2 text-xs text-slate-400">Cancel</button><button disabled={saving} className="btn-switch-primary px-4 py-2 text-[10px]">{saving ? "Creating…" : "Create case"}</button></div></form></div>;
}
