"use client";

import { motion } from "framer-motion";
import { Navbar, Footer } from "../../components/Navigation";
import { 
  FileText, 
  ShieldCheck, 
  Activity, 
  Lock, 
  Fingerprint,
  Layers,
  Info,
  Printer,
  Share2,
  FileDown,
  Database
} from "lucide-react";
import Link from "next/link";
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  Tooltip, 
  ResponsiveContainer,
  Cell
} from 'recharts';

const sampleBiasData = [
  { name: 'Loaded Language', value: 85 },
  { name: 'Fear Appeal', value: 72 },
  { name: 'Straw Man', value: 45 },
  { name: 'False Dilemma', value: 30 },
  { name: 'Tone Skew', value: 65 }
];

const COLORS = ["#F59E0B", "#F59E0B", "#94a3b8", "#f43f5e", "#fb7185"];

export default function SampleAuditPage() {
  return (
    <div className="min-h-screen bg-obsidian text-slate-300 font-sans selection:bg-amber-signal/20 selection:text-amber-signal">
      <Navbar />
      
      {/* Sample Header */}
      <section className="pt-32 pb-12 px-6 md:px-12 bg-gradient-to-b from-[#030712] to-obsidian border-b border-deepslate relative overflow-hidden">
        <div className="absolute inset-0 bg-[linear-gradient(rgba(245,158,11,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(245,158,11,0.02)_1px,transparent_1px)] bg-[size:32px_32px] pointer-events-none" />
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-end gap-8 relative z-10">
          <div className="space-y-4">
            <div className="inline-flex items-center gap-2 border border-amber-signal/30 bg-amber-signal/5 px-4 py-1 font-mono text-[9px] font-bold text-amber-signal uppercase tracking-[0.3em] rounded-none shadow-[0_0_10px_rgba(245,158,11,0.05)]">
              // DEMONSTRATION ENVIRONMENT
            </div>
            <h1 className="text-4xl md:text-5xl font-black text-white mb-2 tracking-tight font-geist uppercase">
              Sample <span className="text-amber-signal">Audit Report.</span>
            </h1>
            <p className="text-slate-400 max-w-xl text-sm font-sans leading-relaxed">
              A high-assurance audit for a leaked video asset. This report demonstrates the evidence trail generated by the Veridex engine.
            </p>
          </div>
          <div className="flex gap-3">
             <button onClick={() => { const w = window as any; w.gtag?.("event", "sample_audit_action_click", { action: "print" }); w.clarity?.("event", "sample_audit_action_click"); }} className="p-3 bg-[#030712] border border-deepslate text-slate-400 hover:text-white transition-all rounded-none"><Printer size={18} /></button>
             <button onClick={() => { const w = window as any; w.gtag?.("event", "sample_audit_action_click", { action: "share" }); w.clarity?.("event", "sample_audit_action_click"); }} className="p-3 bg-[#030712] border border-deepslate text-slate-400 hover:text-white transition-all rounded-none"><Share2 size={18} /></button>
             <button onClick={() => { const w = window as any; w.gtag?.("event", "sample_audit_action_click", { action: "download_pdf" }); w.clarity?.("event", "sample_audit_action_click"); }} className="px-5 py-3 border border-amber-signal bg-amber-signal text-black font-mono text-xs font-bold uppercase tracking-wider hover:bg-transparent hover:text-amber-signal transition-all duration-300 rounded-none shadow-[0_0_12px_rgba(245,158,11,0.15)] flex items-center gap-2"><FileDown size={14} /> Download PDF</button>
          </div>
        </div>
      </section>

      {/* Main Report Container */}
      <section className="pb-24 px-6 md:px-12 bg-[#02050b]">
        <div className="max-w-7xl mx-auto grid lg:grid-cols-[1.4fr,1fr] gap-8">
           
           {/* Left Column: Summary & Evidence */}
           <div className="space-y-8">
              
              {/* Asset Identifiers */}
              <div className="border border-deepslate bg-[#030712] p-8 space-y-6 rounded-none">
                 <div className="flex justify-between items-start border-b border-deepslate pb-4">
                    <h3 className="text-lg font-bold text-white flex items-center gap-3 font-geist uppercase">
                      <FileText className="text-amber-signal" size={18} />
                      Asset Identification
                    </h3>
                    <div className="px-3 py-1 border border-red-500/30 text-[9px] font-mono font-bold text-red-400 bg-red-500/5 rounded-none uppercase tracking-widest">
                      RISK CATEGORY: SYNTHETIC
                    </div>
                 </div>
                 <div className="grid sm:grid-cols-2 gap-6 pt-2 font-mono text-[11px]">
                    <div>
                       <div className="text-[9px] font-bold text-slate-500 uppercase mb-1 tracking-widest">// ASSET NAME</div>
                       <div className="text-slate-200">leaked_speech_candidate_x.mp4</div>
                    </div>
                    <div>
                       <div className="text-[9px] font-bold text-slate-500 uppercase mb-1 tracking-widest">// SHA-256 LEDGER ID</div>
                       <div className="text-amber-signal truncate font-semibold">8f4e2a1b9c3d5e7f8g9h0i1j2k3l4m5n</div>
                    </div>
                    <div>
                       <div className="text-[9px] font-bold text-slate-500 uppercase mb-1 tracking-widest">// AUDIT TIMESTAMP</div>
                       <div className="text-slate-200">2026-03-16 10:45:12 UTC</div>
                    </div>
                    <div>
                       <div className="text-[9px] font-bold text-slate-500 uppercase mb-1 tracking-widest">// ANALYSIS ENGINE</div>
                       <div className="text-slate-200">Veridex v1.1.0-STABLE</div>
                    </div>
                 </div>
              </div>

              {/* Auditor Summary */}
              <div className="border border-red-500/20 bg-red-500/[0.02] p-8 rounded-none">
                 <h3 className="text-lg font-bold text-white mb-4 font-geist uppercase">Auditor's Summary</h3>
                 <p className="text-slate-300 leading-relaxed text-sm font-sans mb-8">
                    The analyzed media contains high-confidence markers of <span className="text-red-400 font-bold">deepfake audio generation (voice cloning)</span>. While the visual layer shows temporal consistency, the spectral frequency analysis of the audio track reveals artifacts consistent with current Diffusion-based synthesis models. Factual claims within the audio are inconsistently correlated with historical public records for the subject.
                 </p>
                 <div className="flex gap-4 font-mono">
                    <div className="border border-deepslate p-4 bg-obsidian flex-1 text-center">
                       <div className="text-xl font-bold text-red-400 mb-1">Low Verity</div>
                       <div className="text-[8px] font-bold text-slate-500 uppercase tracking-widest">Index Value (0.34)</div>
                    </div>
                    <div className="border border-deepslate p-4 bg-obsidian flex-1 text-center">
                       <div className="text-xl font-bold text-red-400 mb-1">Synthetic</div>
                       <div className="text-[8px] font-bold text-slate-500 uppercase tracking-widest">Primary Verdict</div>
                    </div>
                 </div>
              </div>

              {/* Visual Forensic Scans showcase (Using the images) */}
              <div className="border border-deepslate bg-[#030712] p-8 space-y-8 rounded-none">
                <h3 className="text-lg font-bold text-white border-b border-deepslate pb-4 font-geist uppercase flex items-center gap-3">
                  <Activity className="text-amber-signal" size={18} />
                  Visual Evidence Scans
                </h3>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {/* Spectral Anomaly Scan */}
                  <div className="border border-deepslate p-4 space-y-3 bg-[#020617]/50">
                    <div className="flex justify-between items-center text-[9px] font-mono">
                      <span className="text-white font-bold">SIGNAL SCAN // AUDIO</span>
                      <span className="text-red-400 font-bold uppercase">GAN Artifacts (98.2%)</span>
                    </div>
                    <div className="relative h-40 border border-deepslate overflow-hidden bg-black">
                      <img src="/images/spectral_analysis.jpg" alt="Audio Scan" className="w-full h-full object-cover opacity-80" />
                    </div>
                    <p className="text-[10px] text-slate-400 leading-relaxed font-sans">
                      Spectral anomaly detection isolates artificial voice modulation signatures at 12.4kHz.
                    </p>
                  </div>

                  {/* Biometric Mesh Scan */}
                  <div className="border border-deepslate p-4 space-y-3 bg-[#020617]/50">
                    <div className="flex justify-between items-center text-[9px] font-mono">
                      <span className="text-white font-bold">BIOMETRIC GRID // FACE</span>
                      <span className="text-amber-signal font-bold uppercase">Partial Match (98% Acq.)</span>
                    </div>
                    <div className="relative h-40 border border-deepslate overflow-hidden bg-black">
                      <img src="/images/biometric_manifest.jpg" alt="Biometric Scan" className="w-full h-full object-cover opacity-80" />
                    </div>
                    <p className="text-[10px] text-slate-400 leading-relaxed font-sans">
                      Facial mesh vectors analyze micro-expressions for temporal sync errors.
                    </p>
                  </div>
                </div>
              </div>

              {/* Evidence Trail */}
              <div className="border border-deepslate bg-[#030712] p-8 rounded-none">
                 <h3 className="text-lg font-bold text-white mb-8 font-geist uppercase">Forensic Evidence Trail</h3>
                 <div className="space-y-8">
                    {[
                      {
                        module: "Spectral Frequency Audit",
                        finding: "High-frequency GAN artifacts detected in speech pauses.",
                        confidence: "98.2%",
                        status: "CRITICAL"
                      },
                      {
                        module: "Frame Coherence Analysis",
                        finding: "Minor macro-block inconsistencies around facial boundaries.",
                        confidence: "65.4%",
                        status: "WARNING"
                      },
                      {
                        module: "Claim-Level Auditing",
                        finding: "Assertion 'I never signed the treaty' contradicts official UN records.",
                        confidence: "N/A",
                        status: "HALLUCINATION"
                      }
                    ].map((item, i) => (
                      <div key={i} className="flex gap-6 relative font-mono text-[11px]">
                         {i < 2 && <div className="absolute top-10 left-5 w-[1px] h-16 bg-deepslate" />}
                         <div className="h-10 w-10 shrink-0 border border-deepslate bg-obsidian flex items-center justify-center text-amber-signal z-10">
                           <Activity size={16} />
                         </div>
                         <div className="flex-1 pb-8">
                            <div className="flex justify-between items-start mb-2">
                               <h4 className="font-bold text-white uppercase tracking-tight">{item.module}</h4>
                               <span className={`text-[8px] font-bold px-2 py-0.5 border ${item.status === 'CRITICAL' ? 'border-red-500 text-red-400 bg-red-500/5' : 'border-amber-signal text-amber-signal bg-amber-signal/5'}`}>
                                 {item.status}
                               </span>
                            </div>
                            <p className="text-slate-400 mb-2 font-sans text-xs">{item.finding}</p>
                            <div className="text-[9px] font-bold text-slate-500">SIGNAL CONFIDENCE: <span className="text-slate-300">{item.confidence}</span></div>
                         </div>
                      </div>
                    ))}
                 </div>
              </div>

              {/* Claim Decomposition */}
              <div className="border border-deepslate bg-[#030712] p-8 rounded-none">
                 <h3 className="text-lg font-bold text-white mb-8 flex items-center gap-3 font-geist uppercase border-b border-deepslate pb-4">
                   <Layers className="text-amber-signal" size={18} />
                   Claim Decomposition
                 </h3>
                 <div className="space-y-4">
                    {[
                      {
                        claim: "I never signed the treaty.",
                        type: "External Factual Claim",
                        status: "CONTRADICTED",
                        evidence: "UN Treaty Database record #772-B matches subject's digital signature from 2024-05-12."
                      },
                      {
                        claim: "Our internal policy has always been green-first.",
                        type: "Internal Policy Assertion",
                        status: "CONSISTENT",
                        evidence: "Matches 2023 Corporate Sustainability Charter (Public Archive)."
                      },
                      {
                        claim: "The opposition is trying to destroy our economy.",
                        type: "Rhetorical/Subjective Assertion",
                        status: "N/A (BIASED)",
                        evidence: "Flags for 'Fear Appeal' and 'Loaded Language' heuristics."
                      }
                    ].map((item, i) => (
                      <div key={i} className="p-6 bg-obsidian border border-deepslate hover:border-amber-signal/40 transition-colors group">
                        <div className="flex justify-between items-start mb-4 font-mono text-[9px]">
                           <span className="px-2 py-0.5 border border-deepslate text-slate-400 uppercase tracking-widest">
                             {item.type}
                           </span>
                           <span className={`px-2 py-0.5 border ${item.status === 'CONTRADICTED' ? 'border-red-500 text-red-400 bg-red-500/5' : item.status === 'CONSISTENT' ? 'border-verity-green text-verity-green bg-verity-green/5' : 'border-slate-500 text-slate-500 bg-slate-500/5'}`}>
                             {item.status}
                           </span>
                        </div>
                        <h4 className="text-white font-bold mb-2 italic text-sm">"{item.claim}"</h4>
                        <p className="text-xs text-slate-500 leading-relaxed group-hover:text-slate-400 transition-colors font-sans">
                          <span className="font-bold text-slate-700 uppercase mr-2 tracking-tighter">Evidence Trail:</span>
                          {item.evidence}
                        </p>
                      </div>
                    ))}
                 </div>
              </div>

           </div>

           {/* Right Column: Visual Mapping & Trust */}
           <div className="space-y-8">
              
              {/* Bias Map */}
              <div className="border border-deepslate bg-[#030712] p-8 rounded-none">
                 <h3 className="text-lg font-bold text-white mb-8 flex items-center gap-3 font-geist uppercase border-b border-deepslate pb-4">
                   <Activity className="text-amber-signal" size={18} />
                   Rhetorical Bias Mapping
                 </h3>
                 <div className="h-[260px] w-full mt-4 font-mono text-[10px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={sampleBiasData} layout="vertical" margin={{ left: -20, right: 20 }}>
                      <XAxis type="number" hide />
                      <YAxis dataKey="name" type="category" stroke="#94a3b8" fontSize={9} width={100} />
                      <Tooltip 
                        contentStyle={{ backgroundColor: '#020617', border: '1px solid #0f172a', borderRadius: '0' }}
                        itemStyle={{ color: '#F59E0B', fontWeight: 'bold' }}
                      />
                      <Bar dataKey="value" radius={0}>
                        {sampleBiasData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} fillOpacity={0.8} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
                <div className="mt-6 p-4 bg-[#070b19]/40 border border-amber-signal/20 text-xs text-amber-signal leading-relaxed font-sans">
                  Analysis: The content utilizes sophisticated fear appeals and tone-skewing typical of synthetic engagement engines.
                </div>
              </div>

              {/* Copyright Section */}
              <div className="border border-deepslate bg-[#030712] p-8 rounded-none">
                <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-3 font-geist uppercase border-b border-deepslate pb-4">
                  <Lock className="text-red-400" size={18} />
                  Copyright Risk Profile
                </h3>
                <div className="space-y-4">
                   <div className="p-4 bg-obsidian border border-deepslate">
                      <div className="text-[9px] font-bold text-red-400 uppercase mb-1 tracking-widest font-mono">// SIMILARITY MATCH (88.4%)</div>
                      <div className="text-xs text-white font-medium mb-3">Overlap with Protected Archive ID: #P-992-B</div>
                      <Link href="/features/copyright-risk-analysis" className="text-[9px] font-bold text-slate-500 hover:text-white uppercase tracking-widest font-mono">View Detailed Evidence Fragment</Link>
                   </div>
                   <div className="p-4 bg-obsidian border border-deepslate">
                      <div className="text-[9px] font-bold text-slate-500 uppercase mb-1 tracking-widest font-mono">// LICENSE AUDIT</div>
                      <div className="text-xs text-slate-300">No active commercial license record found for SHA-hash matching.</div>
                   </div>
                </div>
              </div>

              {/* Chain-of-custody ledger scan visual */}
              <div className="border border-deepslate bg-[#030712] p-8 space-y-4 rounded-none">
                <h3 className="text-md font-bold text-white font-geist uppercase flex items-center gap-2">
                  <Database className="text-verity-green" size={18} />
                  Evidentiary Registry Proof
                </h3>
                <div className="relative h-40 border border-deepslate overflow-hidden bg-black">
                  <img src="/images/immutable_ledger.jpg" alt="Ledger Registry Scan" className="w-full h-full object-cover opacity-85" />
                </div>
                <p className="text-[10px] text-slate-500 font-sans leading-relaxed">
                  Cryptographically registered on the Veridex blockchain ledger. Tamper-evident proof generated for discovery.
                </p>
              </div>

              {/* Specific Limitations for this Asset */}
              <div className="border border-deepslate bg-[#030712] p-8 rounded-none">
                 <h3 className="text-md font-bold text-white mb-4 flex items-center gap-2 font-geist uppercase">
                   <ShieldCheck className="text-amber-signal" size={18} />
                   Audit Limitations
                 </h3>
                 <ul className="space-y-3 font-mono text-[9px]">
                    {[
                      "Low lighting in source video reduces deepfake detection confidence on the visual plane.",
                      "High audio compression (128kbps) may obscure subtle GAN artifacts.",
                      "Subject's voice profile in the training set is limited to public speeches before 2023."
                    ].map((limit, i) => (
                      <li key={i} className="text-slate-500 leading-relaxed flex gap-3 font-sans text-xs">
                        <span className="text-amber-signal/50 font-bold">•</span>
                        {limit}
                      </li>
                    ))}
                 </ul>
              </div>

              {/* Confidence Notice */}
              <div className="border border-amber-signal/20 bg-amber-signal/[0.01] p-8 rounded-none">
                 <div className="flex gap-4">
                    <Info className="text-amber-signal shrink-0" size={24} />
                    <p className="text-xs text-slate-400 leading-relaxed font-sans">
                      <span className="font-bold text-white block mb-2 uppercase tracking-widest font-geist">Important Confidence Note</span>
                      The results presented here are probabilistic signals from the Veridex engine. This report is forensic support for professional editors, legal counsel, or investigators. Final verification must be performed by a human expert.
                    </p>
                 </div>
                 <Link href="/limitations" className="block mt-6 text-center text-[9px] font-bold text-slate-500 uppercase tracking-[0.2em] hover:text-slate-300 transition-colors font-mono">
                    Read Veridex Limits Disclosure
                  </Link>
              </div>

           </div>

        </div>
      </section>

      {/* Audit CTA */}
      <section className="py-24 px-6 md:px-12 text-center bg-[#030712] border-t border-deepslate">
        <h3 className="text-3xl font-black text-white mb-8 font-geist uppercase">Analyze your own data with <span className="text-amber-signal">Professional Assurance.</span></h3>
        <div className="flex justify-center gap-6">
           <Link href="/request-demo" className="px-8 py-4 border border-amber-signal bg-amber-signal text-black font-mono text-xs font-bold uppercase tracking-wider hover:bg-transparent hover:text-amber-signal transition-all duration-300 rounded-none shadow-[0_0_12px_rgba(245,158,11,0.15)]">Request Full Access</Link>
           <Link href="/audit" className="px-8 py-4 border border-deepslate text-white font-mono text-xs font-bold uppercase tracking-wider hover:bg-white/5 transition-all rounded-none">Run New Audit</Link>
        </div>
      </section>

      <Footer />
    </div>
  );
}
