"use client";

import { motion } from "framer-motion";
import { Navbar, Footer } from "../../components/Navigation";
import { 
  FileText, 
  ShieldCheck, 
  Activity, 
  Search, 
  BarChart3, 
  Lock, 
  Fingerprint,
  Layers,
  Info,
  ChevronRight,
  Printer,
  Share2,
  FileDown
} from "lucide-react";
import Link from "next/link";
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  Cell
} from 'recharts';

const sampleBiasData = [
  { name: 'Loaded Language', value: 85 },
  { name: 'Fear Appeal', value: 72 },
  { name: 'Straw Man', value: 45 },
  { name: 'False Dilemma', value: 30 },
  { name: 'Tone Skew', value: 65 }
];

const COLORS = ["#0d9488", "#2dd4bf", "#94a3b8", "#f43f5e", "#fb7185"];

export default function SampleAuditPage() {
  return (
    <div className="min-h-screen">
      <Navbar />
      
      {/* Sample Header */}
      <section className="pt-32 pb-12 px-4 md:px-12 bg-slate-950">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-end gap-8">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full bg-teal-500/10 px-4 py-1.5 text-[10px] font-black text-teal-400 border border-teal-500/20 mb-6 uppercase tracking-[0.3em]">
              Demonstration Environment
            </div>
            <h1 className="text-4xl md:text-6xl font-black text-white mb-4 tracking-tight">
              Sample <span className="text-gradient">Audit Report.</span>
            </h1>
            <p className="text-slate-400 max-w-xl">
              A high-assurance audit for a leaked video asset. This report demonstrates the evidence trail generated by the Veridex engine.
            </p>
          </div>
          <div className="flex gap-3">
             <button onClick={() => { const w = window as Window & { gtag?: (...args: unknown[]) => void; clarity?: (...args: unknown[]) => void }; w.gtag?.("event", "sample_audit_action_click", { action: "print" }); w.clarity?.("event", "sample_audit_action_click"); }} className="p-3 rounded-xl border border-white/10 text-slate-400 hover:text-white transition-all"><Printer size={20} /></button>
             <button onClick={() => { const w = window as Window & { gtag?: (...args: unknown[]) => void; clarity?: (...args: unknown[]) => void }; w.gtag?.("event", "sample_audit_action_click", { action: "share" }); w.clarity?.("event", "sample_audit_action_click"); }} className="p-3 rounded-xl border border-white/10 text-slate-400 hover:text-white transition-all"><Share2 size={20} /></button>
             <button onClick={() => { const w = window as Window & { gtag?: (...args: unknown[]) => void; clarity?: (...args: unknown[]) => void }; w.gtag?.("event", "sample_audit_action_click", { action: "download_pdf" }); w.clarity?.("event", "sample_audit_action_click"); }} className="btn-primary flex items-center gap-2"><FileDown size={18} /> Download PDF</button>
          </div>
        </div>
      </section>

      {/* Main Report Container */}
      <section className="pb-24 px-4 md:px-12">
        <div className="max-w-7xl mx-auto grid lg:grid-cols-[1.4fr,1fr] gap-8">
           
           {/* Left Column: Summary & Evidence */}
           <div className="space-y-8">
              
              {/* Asset Identifiers */}
              <div className="glass p-8 rounded-3xl border border-white/5 space-y-6">
                 <div className="flex justify-between items-start">
                    <h3 className="text-xl font-bold text-white flex items-center gap-3">
                      <FileText className="text-teal-400" />
                      Asset Identification
                    </h3>
                    <div className="px-3 py-1 rounded-full bg-rose-500/10 border border-rose-500/20 text-[10px] font-black text-rose-500 uppercase tracking-widest">
                      RISK CATEGORY: SYNTHETIC
                    </div>
                 </div>
                 <div className="grid sm:grid-cols-2 gap-6 pt-6 border-t border-white/5">
                    <div>
                       <div className="text-[10px] font-black text-slate-600 uppercase mb-1 tracking-widest">Asset Name</div>
                       <div className="text-sm font-bold text-white">leaked_speech_candidate_x.mp4</div>
                    </div>
                    <div>
                       <div className="text-[10px] font-black text-slate-600 uppercase mb-1 tracking-widest">SHA-256 Ledger ID</div>
                       <div className="text-sm font-mono text-teal-500 truncate">8f4e2a1b9c3d5e7f8g9h0i1j2k3l4m5n</div>
                    </div>
                    <div>
                       <div className="text-[10px] font-black text-slate-600 uppercase mb-1 tracking-widest">Audit Timestamp</div>
                       <div className="text-sm font-bold text-white">2026-03-16 10:45:12 UTC</div>
                    </div>
                    <div>
                       <div className="text-[10px] font-black text-slate-600 uppercase mb-1 tracking-widest">Analysis Engine</div>
                       <div className="text-sm font-bold text-white">Veridex v1.1.0-STABLE</div>
                    </div>
                 </div>
              </div>

              {/* Finding Summary */}
              <div className="glass p-8 rounded-3xl border border-rose-500/20 bg-rose-500/[0.02]">
                 <h3 className="text-xl font-bold text-white mb-6">Auditor's Summary</h3>
                 <p className="text-slate-300 leading-relaxed mb-8">
                    The analyzed media contains high-confidence markers of <span className="text-rose-400 font-bold">deepfake audio generation (voice cloning)</span>. While the visual layer shows temporal consistency, the spectral frequency analysis of the audio track reveals artifacts consistent with current Diffusion-based synthesis models. Factual claims within the audio are inconsistently correlated with historical public records for the subject.
                 </p>
                 <div className="flex gap-4">
                    <div className="glass p-4 rounded-xl border border-white/5 flex-1 text-center">
                       <div className="text-2xl font-black text-rose-500 mb-1">Low Verity</div>
                       <div className="text-[10px] font-black text-slate-500 uppercase">Probabilistic Index (0.34)</div>
                    </div>
                    <div className="glass p-4 rounded-xl border border-white/5 flex-1 text-center">
                       <div className="text-2xl font-black text-rose-500 mb-1">Synthetic</div>
                       <div className="text-[10px] font-black text-slate-500 uppercase">Primary Verdict</div>
                    </div>
                 </div>
              </div>

              {/* Evidence Trail: The "Chain of Reason" */}
              <div className="glass p-8 rounded-3xl border border-white/5">
                 <h3 className="text-xl font-bold text-white mb-8">Forensic Evidence Trail</h3>
                 <div className="space-y-8">
                    {[
                      {
                        module: "Spectral Frequency Audit",
                        finding: "High-frequency GAN artifacts detected in speech pauses.",
                        confidence: "98.2%",
                        status: "CRITICAL"
                      },
                      {
                        module: "Frame Coherence Analysis",
                        finding: "Minor macro-block inconsistencies around facial boundaries.",
                        confidence: "65.4%",
                        status: "WARNING"
                      },
                      {
                        module: "Claim-Level Auditing",
                        finding: "Assertion 'I never signed the treaty' contradicts official UN records.",
                        confidence: "N/A",
                        status: "HALUCINATION"
                      }
                    ].map((item, i) => (
                      <div key={i} className="flex gap-6 relative">
                         {i < 2 && <div className="absolute top-10 left-5 w-0.5 h-16 bg-white/5" />}
                         <div className="h-10 w-10 shrink-0 rounded-full bg-slate-900 border border-white/10 flex items-center justify-center text-teal-500 z-10">
                           <Activity size={18} />
                         </div>
                         <div className="flex-1 pb-8">
                            <div className="flex justify-between items-start mb-2">
                               <h4 className="font-bold text-white text-sm uppercase tracking-tight">{item.module}</h4>
                               <span className={`text-[8px] font-black px-2 py-0.5 rounded-full border ${item.status === 'CRITICAL' ? 'border-rose-500 text-rose-500 bg-rose-500/10' : 'border-amber-500 text-amber-500 bg-amber-500/10'}`}>
                                 {item.status}
                               </span>
                            </div>
                            <p className="text-xs text-slate-400 mb-2">{item.finding}</p>
                            <div className="text-[10px] font-bold text-slate-600">SIGNAL CONFIDENCE: <span className="text-slate-300">{item.confidence}</span></div>
                         </div>
                      </div>
                    ))}
                 </div>
              </div>

              {/* Claim Decomposition */}
              <div className="glass p-8 rounded-3xl border border-white/5">
                 <h3 className="text-xl font-bold text-white mb-8 flex items-center gap-3">
                   <Layers className="text-teal-400" />
                   Claim Decomposition
                 </h3>
                 <div className="space-y-4">
                    {[
                      {
                        claim: "I never signed the treaty.",
                        type: "External Factual Claim",
                        status: "CONTRADICTED",
                        evidence: "UN Treaty Database record #772-B matches subject's digital signature from 2024-05-12."
                      },
                      {
                        claim: "Our internal policy has always been green-first.",
                        type: "Internal Policy Assertion",
                        status: "CONSISTENT",
                        evidence: "Matches 2023 Corporate Sustainability Charter (Public Archive)."
                      },
                      {
                        claim: "The opposition is trying to destroy our economy.",
                        type: "Rhetorical/Subjective Assertion",
                        status: "N/A (BIASED)",
                        evidence: "Flags for 'Fear Appeal' and 'Loaded Language' heuristics."
                      }
                    ].map((item, i) => (
                      <div key={i} className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 hover:border-white/10 transition-colors group">
                        <div className="flex justify-between items-start mb-4">
                           <span className="text-[8px] font-black px-2 py-0.5 rounded-full border border-teal-500/20 text-teal-500 uppercase tracking-widest">
                             {item.type}
                           </span>
                           <span className={`text-[8px] font-black px-2 py-0.5 rounded-full border ${item.status === 'CONTRADICTED' ? 'border-rose-500 text-rose-500 bg-rose-500/10' : item.status === 'CONSISTENT' ? 'border-teal-500 text-teal-500 bg-teal-500/10' : 'border-slate-500 text-slate-500 bg-slate-500/10'}`}>
                             {item.status}
                           </span>
                        </div>
                        <h4 className="text-white font-bold mb-2 italic">"{item.claim}"</h4>
                        <p className="text-xs text-slate-500 leading-relaxed group-hover:text-slate-400 transition-colors">
                          <span className="font-bold text-slate-700 uppercase mr-2 tracking-tighter">Evidence Trail:</span>
                          {item.evidence}
                        </p>
                      </div>
                    ))}
                 </div>
              </div>

           </div>

           {/* Right Column: Visual Mapping & Trust */}
           <div className="space-y-8">
              
              {/* Bias Map */}
              <div className="glass p-8 rounded-3xl border border-white/5">
                 <h3 className="text-xl font-bold text-white mb-8 flex items-center gap-3">
                   <BarChart3 className="text-teal-400" />
                   Rhetorical Bias Mapping
                 </h3>
                 <div className="h-[300px] w-full mt-4">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={sampleBiasData} layout="vertical" margin={{ left: -20, right: 20 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" horizontal={true} vertical={false} />
                      <XAxis type="number" hide />
                      <YAxis dataKey="name" type="category" stroke="#94a3b8" fontSize={10} width={100} />
                      <Tooltip 
                        contentStyle={{ backgroundColor: '#0f172a', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px' }}
                        itemStyle={{ color: '#2dd4bf', fontWeight: 'bold' }}
                      />
                      <Bar dataKey="value" radius={[0, 4, 4, 0]}>
                        {sampleBiasData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
                <div className="mt-6 p-4 rounded-xl bg-teal-500/10 border border-teal-500/20 text-xs text-teal-400 leading-relaxed font-medium">
                  Analysis: The content utilizes sophisticated fear appeals and tone-skewing typical of synthetic engagement engines.
                </div>
              </div>

              {/* Copyright Section */}
              <div className="glass p-8 rounded-3xl border border-white/5">
                <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-3">
                  <Lock className="text-rose-400" />
                  Copyright Risk Profile
                </h3>
                <div className="space-y-4">
                   <div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-500/20">
                      <div className="text-[10px] font-black text-rose-500 uppercase mb-1 tracking-widest">Similarity Match (88.4%)</div>
                      <div className="text-xs text-white font-medium mb-3">Overlap with Protected Archive ID: #P-992-B</div>
                      <Link href="/features/copyright-risk-analysis" className="text-[10px] font-black text-slate-500 hover:text-white uppercase tracking-widest">View Detailed Evidence Fragment</Link>
                   </div>
                   <div className="p-4 rounded-2xl bg-white/5 border border-white/5">
                      <div className="text-[10px] font-black text-slate-500 uppercase mb-1 tracking-widest">License Audit</div>
                      <div className="text-xs text-slate-300">No active commercial license record found for SHA-hash matching.</div>
                   </div>
                </div>
              </div>

              {/* Specific Limitations for this Asset */}
              <div className="glass p-8 rounded-3xl border border-amber-500/10 bg-amber-500/[0.01]">
                 <h3 className="text-md font-bold text-white mb-4 flex items-center gap-2">
                   <ShieldCheck className="text-amber-500" size={18} />
                   Audit Limitations
                 </h3>
                 <ul className="space-y-3">
                    {[
                      "Low lighting in source video reduces deepfake detection confidence on the visual plane.",
                      "High audio compression (128kbps) may obscure subtle GAN artifacts.",
                      "Subject's voice profile in the training set is limited to public speeches before 2023."
                    ].map((limit, i) => (
                      <li key={i} className="text-[10px] text-slate-500 leading-relaxed flex gap-3">
                        <span className="text-amber-500/50">•</span>
                        {limit}
                      </li>
                    ))}
                 </ul>
              </div>

              {/* Confidence Notice */}
              <div className="glass p-8 rounded-3xl border border-amber-500/20 bg-amber-500/[0.02]">
                 <div className="flex gap-4">
                    <Info className="text-amber-500 shrink-0" size={24} />
                    <p className="text-xs text-slate-400 leading-relaxed">
                      <span className="font-bold text-white block mb-2 uppercase tracking-widest">Important Confidence Note</span>
                      The results presented here are probabilistic signals from the Veridex engine. This report is forensic support for professional editors, legal counsel, or investigators. Final verification must be performed by a human expert.
                    </p>
                 </div>
                 <Link href="/limitations" className="block mt-6 text-center text-[10px] font-black text-slate-500 uppercase tracking-[0.2em] hover:text-slate-300 transition-colors">
                    Read Veridex Limits Disclosure
                 </Link>
              </div>

           </div>

        </div>
      </section>

      {/* Audit CTA */}
      <section className="py-24 px-4 md:px-12 text-center bg-slate-900/10 border-t border-white/5">
        <h3 className="text-3xl font-black text-white mb-8">Analyze your own data with <span className="text-gradient">Professional Assurance.</span></h3>
        <div className="flex justify-center gap-6">
           <Link href="/request-demo" onClick={() => { const w = window as Window & { gtag?: (...args: unknown[]) => void; clarity?: (...args: unknown[]) => void }; w.gtag?.("event", "sample_audit_request_access_click", { source: "sample_audit_footer" }); w.clarity?.("event", "sample_audit_request_access_click"); }} className="btn-primary px-10 py-4 text-sm uppercase tracking-widest">Request Full Access</Link>
           <Link href="/audit" className="px-10 py-4 rounded-xl border border-white/10 text-white font-bold hover:bg-white/5 transition-all text-sm uppercase tracking-widest">Run New Audit</Link>
        </div>
      </section>

      <Footer />
    </div>
  );
}

